# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI with Gradle
on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        java-version: ['11', '16', '17']
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish dist
      run: |
        ./gradlew distTar
        ./gradlew distZip
    - uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ matrix.java-version }}
        path: build/distributions/
    - name: Publish to release
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/distributions/PDFUtil-${{ env.RELEASE_VERSION }}.zip
          build/distributions/PDFUtil-${{ env.RELEASE_VERSION }}.tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

